### ISSUE TITLE
Metrics from well known event counters

### ISSUE THREAD

**Issue by ame0410** [JamesNK/aspnetcore-grafana#5]
Hi, I have spent some time figuring out how to expose the metrics listed in https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters. One example is the `current-requests` metric listed under [System.Net.Http counters](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#systemnethttp-counters). I notice that you are using `http_server_active_requests`. The app I tested with runs on .NET 7 and it didn't show any of these. Will it work with .NET 8?

**Comment by JamesNK** [comment]
The dashboard uses metrics added in .NET 8.

They're listed here: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore
