### ISSUE TITLE
Microsoft.AspNetCore.Diagnostics not working?

### ISSUE THREAD

**Issue by ame0410** [JamesNK/aspnetcore-grafana#8]
Hi, I am now in process of upgrading my service to .NET 8.
Adding meters like `Microsoft.AspNetCore.Hosting` and `Microsoft.AspNetCore.Server.Kestrel` give me the relevant metrics like `http_server_request_duration_seconds` and `kestrel_queued_connections`. But when I add the meter `Microsoft.AspNetCore.Diagnostics`, it doesn't show me any metrics from the instrument `aspnetcore.diagnostics.exceptions`. I even tried with generating an exception in my application. Do you have any idea why?

I notice that your Grafana board shows `Total Unhandled Exceptions` which uses `sum(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", error_type!=\"\"})`. Shouldn't this be using `aspnetcore.diagnostics.exceptions`?

**Comment by JamesNK** [comment]
> But when I add the meter `Microsoft.AspNetCore.Diagnostics`, it doesn't show me any metrics from the instrument `aspnetcore.diagnostics.exceptions`. I even tried with generating an exception in my application. Do you have any idea why?

Perhaps the exception isn't being caught by the exception handling middleware?
